config setup

conn ikev2-client
    auto=start
    keyexchange=ikev2
    type=tunnel

    left=%defaultroute
    leftid=%any
    leftauth=psk

    right=<SERVER_IP>
    rightid=<SERVER_IP>
    rightauth=psk

    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!

    rightsubnet=0.0.0.0/0
    leftsourceip=%config